# Generated by Django 3.0.4 on 2020-03-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='userrr',
            new_name='user',
        ),
    ]
